// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NauraaBot.Database;

#nullable disable

namespace NauraaBot.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240304202855_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.27");

            modelBuilder.Entity("NauraaBot.Database.Models.Faction", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Faction");

                    b.HasData(
                        new
                        {
                            ID = "AX",
                            Name = "Axiom"
                        },
                        new
                        {
                            ID = "BR",
                            Name = "Bravos"
                        },
                        new
                        {
                            ID = "LY",
                            Name = "Lyra"
                        },
                        new
                        {
                            ID = "MU",
                            Name = "Muna"
                        },
                        new
                        {
                            ID = "OR",
                            Name = "Ordis"
                        },
                        new
                        {
                            ID = "YZ",
                            Name = "Yzmir"
                        });
                });

            modelBuilder.Entity("NauraaBot.Database.Models.Rarity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Short")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Rarity");

                    b.HasData(
                        new
                        {
                            ID = "COMMON",
                            Name = "Common",
                            Short = "C"
                        },
                        new
                        {
                            ID = "RARE",
                            Name = "Rare",
                            Short = "R"
                        },
                        new
                        {
                            ID = "UNIQUE",
                            Name = "Unique",
                            Short = "U"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
